
apiVersion: v1
data:
  local--kafka: eyJrYWZrYV9hZG1pbiI6ImFkbWluOmFkbWluLXNlY3JldCIsImthZmthX3VzZXJfMSI6InVzZXIxOnVzZXIxcGFzcyIsImthZmthX3VzZXJfMiI6InVzZXIyOnVzZXIycGFzcyIsImthZmthX3VzZXJfMyI6Im15LXVzZXI6bXl1c2VycGFzcyJ9
kind: Secret
metadata:
  labels:
    fwss.freshworks.com/secrets-managed: "true"
  name: local--kafka
type: Opaque